name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        default: 1.0.0
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "refs/tags/${{ github.event.inputs.tag }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: tetrate-${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: 
          draft: false
          prerelease: false
    
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: tetrate-${{ github.event.inputs.tag }}
