name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Bump Version
        default: v1.0.0
        required: true
  push:
    tags:
      - '[0-9]+.[0-9]+.0'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "refs/tags/${{ github.event.inputs.version }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: tetrate-${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 
          draft: false
          prerelease: false

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/} | rev | cut -d . -f2- | rev)"
        id: extract_tag
    
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: tetrate-${{ steps.extract_tag.outputs.tag }}
